### ISSUE TITLE
Install fails using pip3

### ISSUE THREAD

**Issue by bennierex** [steemit/steem-python#136]
I can't install without having *pipenv* installed first. The readme suggests it can also be installed using *pip*. 
This needs to be either fixed, or the installation instructions should be changed as to only mention *pipenv*.

```bash
$ git clone https://github.com/steemit/steem-python.git
$ cd ./steem-python
$ pip install .
Processing /Users/ben/_tmp/steem-python
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l7/blkfgn9n0qxgvx5tls9ydtf00000gn/T/pip-e_fkh2zw-build/setup.py", line 2, in <module>
        from pipenv.project import Project
    ModuleNotFoundError: No module named 'pipenv'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l7/blkfgn9n0qxgvx5tls9ydtf00000gn/T/pip-e_fkh2zw-build/
```

**Comment by sneak** [comment]
Installing with `pip3` requires `pipenv` to be installed (even if you're not using pipenv to manage your virtualenv) because the authoritative list of requirements is stored in the Pipfile, not an old-style requirements.txt, and the `pipenv` module is required to parse that and put it into setuptools-land.  You *can* install using only `pip3` but it needs the `pipenv` module for parsing.

`pip3 install pipenv` (or alternately `pip3 install --user pipenv` for a non-systemwide installation) will solve your problem, then `pip3 install .` will work.

**Comment by bennierex** [comment]
Thanks for updating the readme on this.
